# Generated by Django 4.2.2 on 2023-06-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
