# Generated by Django 4.2.2 on 2023-06-15 08:57

import Blog_Module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog_Module.models.upload_image_path),
        ),
    ]
