# Generated by Django 4.2.2 on 2023-06-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
