# Generated by Django 4.2.2 on 2023-06-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0009_alter_profile_image'),
        ('Blog_Module', '0008_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Module.profile'),
        ),
    ]
