# Generated by Django 4.2.2 on 2023-07-09 18:38

import Blog_Module.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0009_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog_Module.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_Post', to='Blog_Module.category'),
        ),
    ]
