# Generated by Django 4.2.2 on 2023-07-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0010_category_image_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
