# Generated by Django 4.2.2 on 2023-07-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0011_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
