# Generated by Django 4.2.2 on 2023-06-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
