# Generated by Django 4.2.2 on 2023-06-15 09:03

import Account_Module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Account_Module.models.upload_image_path),
        ),
    ]
